# Generated by Django 5.1.7 on 2025-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('Industrial', 'Industrial'), ('Commercial', 'Commercial'), ('Medical', 'Medical')], max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Quantity available in stock')),
                ('retailer_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
