# Generated by Django 5.1.7 on 2025-03-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_gasproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasproduct',
            name='weight',
            field=models.CharField(default=52, max_length=50),
            preserve_default=False,
        ),
    ]
