# Generated by Django 5.1.7 on 2025-03-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_gasproduct_weight'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GasProduct',
            new_name='Gas',
        ),
    ]
