# Generated by Django 5.0.4 on 2025-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_gasproduct_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=20, help_text='Initial quantity added'),
            preserve_default=False,
        ),
    ]
