# Generated by Django 5.0.4 on 2025-03-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_gas_initial_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gas',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity available in stock', null=True),
        ),
    ]
