# Generated by Django 5.1.7 on 2025-03-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('agency_name', models.TextField()),
                ('agency_start_year', models.IntegerField()),
                ('agent_image', models.ImageField(blank=True, null=True, upload_to='agent_images/')),
                ('agent_idproof', models.ImageField(blank=True, null=True, upload_to='idproof_agent/')),
                ('address', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('password', models.CharField(max_length=100)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('agent_approved_status', models.IntegerField(default=0)),
            ],
        ),
    ]
