# Generated by Django 5.1.7 on 2025-03-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_rename_gasproduct_gas'),
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasBookAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.agent')),
                ('gas_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.gas')),
            ],
        ),
    ]
