# Generated by Django 5.1.7 on 2025-03-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='idproof_User',
            field=models.ImageField(default=11, upload_to='idproof_User/'),
            preserve_default=False,
        ),
    ]
