# Generated by Django 5.1.7 on 2025-03-19 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_userbookgas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookgas',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
            preserve_default=False,
        ),
    ]
