# Generated by Django 5.1.7 on 2025-03-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userbookgas_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookGas',
        ),
    ]
