# Generated by Django 5.1.7 on 2025-03-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_userbookgas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookgas',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userbookgas',
            name='user_name',
        ),
    ]
