# Generated by Django 5.0.4 on 2025-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_userbookgas_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookgas',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
